package: indexnow
version: '1.0.0'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/indexnow


requires:
    php:
        version: '^8'
    redaxo: ^5.13
    packages:
        structure: true
        mediapool: true

page:
    title: translate:indexnow_title
    hidden: true


pages:
    system/indexnow:
        title: translate:indexnow_title
        icon: rex-icon fa-gear
        perm: indexnow[]

default_config:
    apikey: ""
